# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.3
        with:
        # Required - kibot config file
          config: automation/docs.kibot.lst
        # optional - prefix to output defined in config
          dir: docs
        # optional - schematic file
          schema: 'unicorn-mx/unicorn/unicorn.sch'
        # optional - PCB design file
          board: 'unicorn-mx/unicorn/unicorn.kicad_pcb'
        # optional - verbose output info
          verbose: 1
      # Runs a set of commands using the runners shell
      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs
